### ISSUE TITLE
拓展url有问题

### ISSUE THREAD

**Issue by nsnans** [web-dahuyou/NiceTab#1]
![image](https://github.com/web-dahuyou/NiceTab/assets/68949154/8fd3ab6b-af24-4bfa-bdd6-6d143da92862)
![image](https://github.com/web-dahuyou/NiceTab/assets/68949154/65197ba3-80a7-44db-9e19-5fe7b0216d7a)

删掉`#`部分

![image](https://github.com/web-dahuyou/NiceTab/assets/68949154/9ef29308-1a46-48f5-9100-266b2ca4e713)

![image](https://github.com/web-dahuyou/NiceTab/assets/68949154/1c178239-da3b-4f4c-b46c-6a7024747df5)

**Comment by web-dahuyou** [comment]
感谢反馈, 我的电脑测试是正常的, 就发布了! 

这么看来你的浏览器不支持这种格式。

麻烦你试试把 `/options.html/#/home` 里 `#` 前面的 `/` 去掉后是否正常，如果正常的话，我就更新一版， 谢谢。

**Comment by web-dahuyou** [comment]
OK, 我把 `#` 前面的 `/` 去掉了, 已经提交审核了,  审核通过大概需要一天时间.
