### ISSUE TITLE
配置同步

### ISSUE THREAD

**Issue by Tray2499** [web-dahuyou/NiceTab#102]
当前插件同步并不包括插件本身的设置，并且也没有能导出插件配置的地方，是否考虑加强一下同步功能，直接将插件的配置项也进行同步？

**Comment by web-dahuyou** [comment]
这个后面会加，之前没加是因为配置项不多，随着配置项的增多，可以逐步添加配置项的本地导出和远程同步功能。

**Comment by web-dahuyou** [comment]
v2.5.13 已支持配置项的导入导出和远程同步功能。

已 release 到代码仓库，扩展商店缓几天再发布。

**Comment by Tray2499** [comment]
用上了，👍👍👍
