### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#12]
UP你好，我的issue被关闭了，怕你看不到， 只好开个新的。
首先感谢你的辛勤劳动和快速响应！
试用了1.5.1，发现还是有问题，可能是我没有表达清楚。
我想要的去重功能，不是只针对发送的页面和组，而是将发送的页面或组与仓库已有的比较， 如果有重复的页面，就舍弃不再重复入仓，如果是组同名，就把发送组内的页面与仓库组内的页面比较，只入仓那些没有的页面到仓库同名组里面。这样仓库就不会像目前这样出现多个同名组。
还有，对仓库已有的组进行排序，这个功能应该是还没有添加吧？

**Comment by web-dahuyou** [comment]
你说的意思我明白，考虑到如果发送时就与列表中的标签组或标签页合并，那么就分散到各个标签组了，看不到发送后的效果。

所以目前的实现是发送标签组和标签页时，会一起展示（暂未分散合并），并自动定位到刚发送的那些标签组，便于同时查看；然后根据需要手动移动穿越标签组或者标签页到目标组（移动到的弹窗中添加了是否合并的选项）。

我在思考一种方案：
- 添加一个置顶的分类作为中转站，所有发送的标签页先到中转站而不是默认第一个分类（因为扩展图标右键时并不知道标签页应该属于哪个分类），然后自己主动去操作合并或者移动穿越
- 发送标签页时，与列表进行比对自动合并，这种方式需在设置项中添加提示文案，告知合并后的效果

最后，你提到的按字母排序功能暂时没有这个计划，我个人觉得这种根据条件排序是用来查看的，与拖拽排序相冲突，除非按字母排序不是一种状态而是一种一次性操作（不知道我表达的是否清楚）

**Comment by Mizanzhang** [comment]
1. 你思考的这个方案非常nice！ 也更实用，这个中转站可以有多个（完美状态），对应不同的工作主题。完成该项工作主题后，再“一键”或者只对那些打勾的条目入库，入库时才根据域名或所在组名各找各妈对号入库/入组。天啊太棒了，早日实现吧。
2. 关于排序，我完全理解你的意思。那可否综合一下：星标或锁定的组按拖曳排序，其他的加个按钮一键按字母排序。请理解强迫症的那点偏执吧，thx。

**Comment by web-dahuyou** [comment]
关于排序，可以添加一次性排序操作的按钮，排序完就是最终状态了，之前的状态就丢弃了，如果后续对标签组进行拖拽或者移动穿越操作，就会以新的状态为准，想要再次排序，就再点一下排序按钮。每次操作就是一次终态。

**Comment by Mizanzhang** [comment]
排序做成这样，对我来说完全可以接受！至于出于照顾其他人，是否采纳我建议的把星标或锁定的对排序免疫，就由您来定夺了。两者皆可 , 期待早日实现！
