### ISSUE TITLE
改进建议：中转站增加 “一键移动所有标签组” 和 “一键移动所有选中标签” 的按钮

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#16]
UP主你好，经过这一轮改进，NIce-tab已经能作为日用软件了，非常感谢您的劳动。
目前仍有一点大幅提升效率的改进建议，就是如题的  中转站增加 “一键移动所有标签组” 和“一键移动所有选中的标签”的按钮， 而不是像目前1.6.0的挨个标签组去点击移动，希望您能采纳。 谢谢
“一键移动所有选中的标签”是为了满足同时选中若干组内若干标签的情况。
BTW，个人感觉新logo不如原logo好看， 不过无伤大雅 ：）

**Comment by web-dahuyou** [comment]
话说，我v1.6.0版本的发布还在审核中呢，你是在releases 里面直接下载的压缩包吗？
关于logo, 这就很尴尬了，之前的logo我随意放上去的，现在的logo是为了保持跟推广图中的一致。。。主要是我不会设计（-_-）

**Comment by Mizanzhang** [comment]
关于 “一键移动标签组” ：我的想法是，一键把中转站里所有东西移动到其他自定的分类里，移动的机制还是现有的 “移动到”  功能的机制，即组找组，是否合并去重自己打钩。 说白了，就是简化目前的逐个组去点那个“移动到”功能，一键搞定。

**Comment by Mizanzhang** [comment]
关于 “一键移动所有选中的标签页” ：  我的想法还是不用考虑标签穿越组， 就还是以组为单元去移动到分类里， 唯一的区别：不是移动整组东西，只是移动组内选中的那些（目前这个功能已有，但只能是单组操作）。说白了，就是把目前需要逐个组去操作的步骤 加上个批处理。

**Comment by Mizanzhang** [comment]
总而言之，这两个功能都是在现有功能基础上，把单组移动到其他的分类的操作 加个批处理，就不用逐个组去操作这么繁琐了。两者的区别只是：一个是把整个组内的东西全部移动，另一个是把组内选中的以组为单位移动。

**Comment by Mizanzhang** [comment]
总而言之，这两个功能都是在现有功能基础上，把单组移动到其他的分类的操作 加个批处理，就不用逐个组去操作这么繁琐了。两者的区别只是：一个是把整个组内的东西全部移动，另一个是把组内选中的以组为单位移动。

**Comment by web-dahuyou** [comment]
功能实现好说，我得思考下交互按钮放哪儿，功能多了就只能在左侧列表上采用右键菜单了

**Comment by Mizanzhang** [comment]
建议放在右栏 第一组的再往上的置顶行，不管往下滚动浏览到哪组 该行都是置顶可见

**Comment by Mizanzhang** [comment]
弱弱打听一下上述功能进展情况

**Comment by web-dahuyou** [comment]
这个功能暂时没规划，先做了合并导入和远程同步功能，新版本 2.0.0 已经发布，Edge浏览器得等一周的审核时间。

**Comment by web-dahuyou** [comment]
v2.0.1 支持一键移动穿越当前分类下所有标签组，至于跨组多选标签页的功能后续再看需求情况。 #22
