### ISSUE TITLE
bug report 1.6.0

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#17]
下列设置并保存，但是在列表中点击单个标签打开时，该标签没有从NiceTab列表中删除

恢复标签页/标签组时-是否自动删除标签页：从NiceTab列表中删除（仍保留固定标签页）

**Comment by web-dahuyou** [comment]
这个功能最开始本想加上的，如果有这个需求，那就给加上吧，配置项越来越多了。。。

**Comment by Mizanzhang** [comment]
呵呵，摩天楼就是这样建起来的

**Comment by Mizanzhang** [comment]
不过，这个功能没有我在#16提到的 中转站增加 “一键移动所有标签组” 和 “一键移动所有选中标签” 的按钮 的功能重要，还是优先开发那个吧，谢谢！

**Comment by web-dahuyou** [comment]
新版本已发布
