### ISSUE TITLE
产品交流

### ISSUE THREAD

**Issue by Horace-Ho** [web-dahuyou/NiceTab#18]
**问题描述：**

最近在工作中，我遇到了一个需求：我有两台设备，分别在公司和家里。下班时未完成的工作（如文档和重要页面）可能会被遗忘，回家继续或第二天继续时，历史记录会变得非常庞杂，不容易找到需要的页面。因此，我开发了一个功能，用于一键收集当前标签，并将数据POST到服务器，以便在其他设备上访问。

**现状：**

目前，这个功能还没有实现用户鉴权和云空间分配，服务器地址是硬编码的，不需要密码，只有我自己在使用。

**需求：**

1. **用户鉴权：** 我希望在功能中加入用户鉴权机制，以确保数据的安全性和私密性。
2. **云空间分配：** 目前没有针对云空间的分配方案。我希望找到一个无需成本的云空间，能够支持扩展其他用户的使用。
3. **开源计划：** 我计划将这个项目开源，因此希望减少实际的经济成本，并且提供给更多用户使用。

**问题：**

- 如何实现用户鉴权并且在功能中有效集成？
- 有没有推荐的免费云存储服务，可以支持开源项目，并满足上述需求？

希望收到建议和帮助！

**Comment by web-dahuyou** [comment]
@Horace-Ho 下一个版本，我会把标签列表数据同步到gitee和github的gists代码片段中，这个只需要用户配置自己的gitee和github 的 accessToken，并且 accessToken 设置权限范围为gists操作即可（参考N-tab 插件）

- 最近工作比较忙，偶尔抽点时间写一点，远程同步功能快要发布了
- 至于云服务器，我之前担心如果不是长久稳定的云服务器，一旦云服务器到期或者不可用了，数据就丢了

**Comment by web-dahuyou** [comment]
v2.0.0 已支持远程同步功能了 #19
