### ISSUE TITLE
星标后，再取消星标，Group没有按照时间排序了

### ISSUE THREAD

**Issue by nsnans** [web-dahuyou/NiceTab#2]
![image](https://github.com/web-dahuyou/NiceTab/assets/68949154/28da69b1-e35d-451d-9f81-9296437ddad7)

应该需要添加一个根据createTime的sort

https://github.com/web-dahuyou/NiceTab/blob/354811c604cddf00ef1e7724e154f99ab1d585ca/entrypoints/options/recycleBin/index.tsx#L157-L174

**Comment by web-dahuyou** [comment]
- `OneTab` 插件和 `N-Tab` 插件的星标都是置顶功能， `OneTab` 非星标是按时间排序，`N-Tab` 取消星标会放置到非星标的首位。
- 这里我的交互逻辑跟 `N-Tab` 插件的一致，置顶排最前面，取消置顶则放置到非星标首位； 我这里的时间基本上是作为展示创建时间用的。
- 如果交互逻辑是 星标状态单独时间排序，非星标状态单独时间排序 的话，可以使用你的方案。

**Comment by web-dahuyou** [comment]
嗯嗯，还有一种情况需要考虑

OneTab 是不支持标签组自定义排序的，而NiceTab 由于支持拖拽排序、快捷键上下移动和移动穿越功能，所以交互操作不能按照时间来排序
