### ISSUE TITLE
关于“拉取合并推送” 这个同步功能的探讨

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#20]
忽悠哥，恭喜工程又往前迈进一大步。但我仍想对标题所述功能提点建议，知道你是为了方便用户贴心地把几个动作整合，这对标签增量很有用，然而它应对不了标签减少的场景。
举例说，
用户在家和公司两台电脑办公，早上公司晚上家。假设两台电脑的标签都进行了同步。
早上，用户在公司一打开浏览器即进行“拉取合并推送”，然后经过一天工作，删除了A若干标签，增加了B若干标签，下班关电脑前进行“推送覆盖远程”。
晚上，用户在家电脑，用“拉取合并推送”功能，又把早上删除的A若干标签（在家电脑本地还有存档）同时恢复到本地和远程，违反用户意图。

所以建议：修改“拉取同步推送” 为“拉取覆盖本地” 或者更完美的：再增加一个“拉取覆盖本地”功能。
然后养成以下习惯
早上公司，打开电脑-拉取覆盖本地-工作-“推送覆盖远程”-关电脑
早上家，打开电脑-拉取覆盖本地-工作-“推送覆盖远程”-关电脑
即，不管在哪里，打开浏览器第一时间“拉取覆盖本地”，关电脑前“推送覆盖远程”，方能实现真正的“同步”。

**Comment by web-dahuyou** [comment]
这个功能其实我偷懒了。

真正要实现差异化同步，不是覆盖操作，而是根据新旧版本进行对比，类似于vue的diff对比， 同一个元素在旧版本存在，而新的版本不存在，说明就是删除了元素，新版本新增的元素在旧版本中没有，说明就是新增。

最初其实只是想加个远程同步存储防丢失的，恰好加了合并导入功能，顺便就复用了这个合并功能，你说的意思我在做的时候就考虑过了，暂时先实现同步功能再说，后面有空的话，就采用差异化对比的方式合并。

另外，这里面合并的时候，考虑到OneTab导入的情况，所以都没对未命名的分组进行合并。

**Comment by Mizanzhang** [comment]
是的，我确实是那么想的，但是考虑到你的工作量，退而求其次，没敢那么写。 目前这样也能凑合用，所以，能否优先考虑我另帖提议的“一键转移中转站所有标签组”的功能？

**Comment by web-dahuyou** [comment]
现在工作每天早9到晚10，尽量抽点时间码几行代码，没有UI设计，很伤脑筋啊~

**Comment by Mizanzhang** [comment]
功能强大，稳定高效才是最重要的， 颜值嘛低一点也能接受，看久了也习惯了，现在看那个LOGO也没当初那么丑了。 ：）

看你这么忙， 应该也是大公司的资深程序猿了， 大公司应该不缺UI设计师啊，正好借这个项目向心仪的美女UI师展开攻势。

**Comment by web-dahuyou** [comment]
后续看看能不能网上找个合得来的UI开发点其他的产品。

**Comment by web-dahuyou** [comment]
v2.0.1 新增了拉取远程覆盖本地的功能按钮，保留拉取合并推送的功能按钮。

决定合并时还是不做移除操作了，这一块功能并不想做的太复杂，只保证双端数据都不丢失就行了。

另外，v2.0.0 版本时预规划了自动同步的开关，后续看情况要不要支持。
