### ISSUE TITLE
迫切需要“一键转移中转站所有标签组到其他分类”的功能！

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#21]
忽悠哥你好，经过这段时间的使用，我愈发觉得 “一键转移中转站所有标签组到其他分类”这个功能太重要了，再次呼吁早日实现。
描述一下我的实际运用场景：
我同时在处理几个项目，不同项目需要查询不同的资料，假设项目1～项目5，我对应的创建了5个分类。
假设我今天计划处理项目3，下班了还没弄完，然后想把所有tabs归档到项目3以便后续继续。这时我需要一键发送所有标签组到中转站，接着从中转站归档到项目3，这时要了我的亲命了，我只能逐个的移动标签组，逐个逐个的点选择点确定（确定按钮还不能打回车只能鼠标点击）。标签组一多，我就吐血了。所以这个功能太迫切需要了。何况现在的拉取合并功能，已经实现了同样的算法。稍微调整一下即可实现这个功能了。叩谢

**Comment by web-dahuyou** [comment]
哈哈哈，就你最活跃，我咋感觉这是专门- 给你开发的呢🙄

**Comment by Mizanzhang** [comment]
呵呵，你都不知道，这段时间里，我每天都要刷新这个project好几次，望眼欲穿啊。这样的插件我已经渴望多年了，一直没找到勉强能用的，现在好不容易遇到这个无比接近心中理想的。也不是没想过自己做，奈何编程水平有限，没有教程，看都看不懂。

**Comment by Mizanzhang** [comment]
onetab, N-tab都用过，功能实在简陋。one tab group，界面美化整得高大上，功能也还凑合，但是连最基本的稳定都弄不好， 标签也一上百就极易崩溃。

**Comment by web-dahuyou** [comment]
就像我在README介绍里写的那样，最后我才决定自己开发一个，按照我自己的想法来的，本来之前想着写来自己用用就算了。

你有身边的朋友在用吗，他们有没有啥建议？

**Comment by Mizanzhang** [comment]
抱歉，暂时没有，他们觉得onetab之流已经够用了，不像我这深度网虫。尤其是看到我这近千个标签，眼神就像在看异星生物。
眼前这些已知的待开发功能，已经够你喝一壶了，你还有精力考虑别的？ 而且这些功能都实现的话，这个插件已足以屌大所有同类，傲视群雄了。

**Comment by web-dahuyou** [comment]
由于时间不充裕，仓促开发的，我对这个插件还不是很满意，后面慢慢优化吧。

**Comment by web-dahuyou** [comment]
v2.0.1 已新增一键移动穿越当前分类下所有标签组的功能
