### ISSUE TITLE
拒绝重复标签页

### ISSUE THREAD

**Issue by Andyear** [web-dahuyou/NiceTab#3]
希望可以添加标签页是否可以重复的功能

**Comment by web-dahuyou** [comment]
目前在这些操作加了是否去重的功能：
- 发送标签页时可选中合并标签组或者标签页去重
- 标签组/标签页 移动穿越 时可选择是否合并去重

后续计划在标签组上新增去重按钮，点击进行去重

**Comment by web-dahuyou** [comment]
hello @Andyear , 目前v1.5.2 版本在标签组上新增了去重按钮，可对标签组进行手动去重功能

至于发送标签页时与列表页比对去重的功能，跟其他小伙伴进行过讨论（可查看=> #12）, 后续按照讨论中的思路进行实现

**Comment by web-dahuyou** [comment]
v1.6.0 版本已发布 #13 #14 #15 ，支持标签组，标签页与中转站中的标签组和标签页合并去重
