### ISSUE TITLE
远程同步出现大量重复项

### ISSUE THREAD

**Issue by rime88999** [web-dahuyou/NiceTab#31]
<img width="254" alt="屏幕截图 2024-09-04 165527" src="https://github.com/user-attachments/assets/a2844a82-0abe-474f-beda-4df92a45c843">

原有约1800条标签页，我发现这个问题时约有近8000条。我在三个设备浏览器上使用nicetab的同步功能，多设备的记录有时无法正常合并。我使用电脑复现这个问题时，发现新增标签页，使用“拉取远程数据，与本地合并，然后推送”，有时也会出现无法合并的现象；并且多次使用“拉取远程数据，与本地合并，然后推送”，在标签页数量达到5400后，合并功能又恢复正常。

感谢作者，恢复标签页自动创建组非常好用；标签页管理增删修改体验很好。
另，希望“标签导出”界面不要自动生成导出内容，而是点击导出按钮后再生成导出内容。在标签页较多的情况下，打开“导入导出”页面，电脑端chrome会弹出标签页等待提示，加载非常慢。
绝大多数时候我都是随用随存的，标签组名称对于有价值的标签组是重要的，但对于大部分标签组用处并不大，是否可以默认不显示标签组名称，从而突出有价值的标签组，优化排版

**Comment by web-dahuyou** [comment]
感谢建议~~~

你这种情况应该是未命名的标签组很多
- 由于标签组名称默认是 Unnamed Group
- 合并分组的规则是同名分组进行合并
- niceTab 格式导入没有标签组名称，为了防止合并标签组时将 oneTab 的所有分组合成一个，所以没有对 Unnamed Group 分组进行合并操作，于是就会出现 Unnamed Group 分组成倍增加

后面我优化下，niceTab 导入的分组用随机串来创建名称吧，就不会出现这种情况了。

关于导入/导出页面，后面我改一下，默认不生成导出内容。

**Comment by web-dahuyou** [comment]
新版本对标签组命名规则做了调整
