### ISSUE TITLE
关于同步问题咨询

### ISSUE THREAD

**Issue by leiiiooo** [web-dahuyou/NiceTab#34]
1. 我的Microsoft Edge浏览器和Chrome浏览器登录了相同token的github账号（token 权限只勾选 gists 操作）
2. 在我的Edge上，我强制同步到github
3. 在Chrome我尝试同步获取
4. 但是我的Chrome并为获取到Edge里面的内容。（仍然是空的，Chrome一次也没有在本地保存过）

**Comment by leiiiooo** [comment]
Edge：
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/2f0abf30-a477-4e03-8d6d-55230ba23e6c">

Chrome：
<img width="899" alt="image" src="https://github.com/user-attachments/assets/0e1ca170-88bc-4bcd-8910-726b2b5971fa">

**Comment by web-dahuyou** [comment]
我理解下，看你截图的意思是历史记录没有同步过来还是标签页数据没有同步过来？请切到列表页查看下数据。

如果是标签页数据没有同步过来，我抽时间测试一下。

如果只是历史记录没有同步过来，那属于正常情况！目前只同步了标签页数据，其他信息都未做同步。

**Comment by leiiiooo** [comment]
> 我理解下，看你截图的意思是历史记录没有同步过来还是标签页数据没有同步过来？请切到列表页查看下数据。
> 
> 如果是标签页数据没有同步过来，我抽时间测试一下。
> 
> 如果只是历史记录没有同步过来，那属于正常情况！目前只同步了标签页数据，其他信息都未做同步。

Chrome目前是这种情况，不知道和你的哪个是对应的🤔
<img width="720" alt="image" src="https://github.com/user-attachments/assets/1673e67b-1c21-4737-969e-f601361488df">

**Comment by web-dahuyou** [comment]
你使用的是哪个版本，目前最新版v2.2.2  

如果是旧版本的话，接口请求失败时可能会清空列表

**Comment by leiiiooo** [comment]
Edge:
<img width="608" alt="image" src="https://github.com/user-attachments/assets/6daf6b31-debd-4e18-81e5-c757a80eb6d8">

Chrome:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/11eb7ddc-1f00-4aa7-8f33-c4980fa8da8b">

**Comment by web-dahuyou** [comment]
现在同步还是空的吗，登录到 gists 页面看看远程的有数据不

**Comment by leiiiooo** [comment]
> 现在同步还是空的吗，登录到 gists 页面看看远程的有数据不
> 
> 如果有问题，可以加我联系方式，或者邮件发送给我你的联系方式，到时候方便排查。

https://gist.github.com/leiiiooo/5380d19125cc1e7a6083e90d2d9242b4 有的

**Comment by web-dahuyou** [comment]
找到问题了，github 的api 跟 gitee 的 api 基本上完全一致

但是在获取 gists 列表时，github 少了一个字段，竟然不返回content内容。不仔细看，都发现不了啊~~~

我明天给处理下，等新版本发布后你再试一试

**Comment by leiiiooo** [comment]
worked, thanks
