### ISSUE TITLE
无法发送标签页

### ISSUE THREAD

**Issue by Resurgence27** [web-dahuyou/NiceTab#39]
点击发送**标签页没有反应，请问如何解决

**Comment by web-dahuyou** [comment]
哪个版本，建议升级版本尝试

**Comment by Resurgence27** [comment]
> 哪个版本，建议升级版本尝试

是Chrome商店里直接安装的插件版本，或许因为有其他onetab插件冲突？

**Comment by web-dahuyou** [comment]
请问现在操作正常吗, v2.4.0 还增加了快捷命令, 可通过快捷键发送标签页以及打开管理后台.
