### ISSUE TITLE
隐藏边栏更加简洁

### ISSUE THREAD

**Issue by kuai520** [web-dahuyou/NiceTab#4]
希望加入隐藏侧边栏和顶部栏按钮或鼠标滑过显示 点star了

**Comment by web-dahuyou** [comment]
这个功能后面可以加上

**Comment by web-dahuyou** [comment]
hello @kuai520 , v1.5.2已经新增该功能 #11 
[添加侧边栏折叠功能](https://github.com/web-dahuyou/NiceTab/pull/11/commits/f3894ec6fe58452aac2bf5aa81fe777749742962)
