### ISSUE TITLE
增加标签页数量设置

### ISSUE THREAD

**Issue by Andyear** [web-dahuyou/NiceTab#41]
在更新到 2.2.6 版本后，出现了“分类中标签页数量超过预定值，将只展示单个标签组”的提示。但当前未找到可以设置预定值的选项。希望在设置页面中能够提供一个配置选项，以设置所有分类的标签页显示预定值。具体来说，应该允许为每个分类单独设置预定值，如果某个分类没有单独设置，则使用全局预定值作为默认。

**Comment by web-dahuyou** [comment]
添加这个按钮是为了考虑大数据量时渲染卡顿而设置的，之所以不放开这个设置，是防止设置过大，大量标签页渲染导致页面卡死

**Comment by Andyear** [comment]
那个展示更多按钮还要手动点击，其实可以考虑引入滚动加载，并且恢复之前版本那种显示方式。引入滚动加载后在大量标签页下也不会卡死，也不用手动点击展示更多。体验上要好很多。类似[element的Infinite Scroll](https://element-plus.org/zh-CN/component/infinite-scroll.html#%E6%8C%87%E4%BB%A4)

**Comment by Mizanzhang** [comment]
大忽悠哥，理解这样做的意图， 但是提两个建议， 1. 建议“显示更多”按钮的阈值设置到超过显示满屏时的数值，而不是现在的还有半屏空白就已经折叠显示了，每切换一次分类就要点击一次显示更多，繁琐要死，我记得以前700个标签同时显示加载也没有卡顿的现象啊。   2. 如果硬要坚持这个做法，建议增强一下查找功能，以前显示所有标签的时候，可以查找到目标标签，现在搜索功能只能找到分类，找不到具体的标签，搜索功能废了。

**Comment by web-dahuyou** [comment]
OK，下一版本我把“展示更多”按钮给去掉吧，我上次弄了两个版本，选择了这个版本，忘了搜索这个事了

**Comment by web-dahuyou** [comment]
v2.2.7 改动内容：
- 删除了 “展示更多” 按钮
- 保留了当前选中分类下标签页超过预设值则只展示选中的标签组的逻辑
- 新增了当前分类中标签页数量阈值设置项，根据情况自行设置（默认值 500）
