### ISSUE TITLE
希望在列表页里点击标签页可以直接跳转到对应的标签页，而不是还停留在列表页

### ISSUE THREAD

**Issue by GitHub-Xzhi** [web-dahuyou/NiceTab#44]

**Comment by web-dahuyou** [comment]
这个交互每个人的需求不同的，比如我会在列表页同时点好几个相关的标签页打开，如果每次点击都跳转的话，我还要返回列表页再一个个这么操作，很麻烦的。

当然，这个得看看点击跳转需求的人多不多，如果多的话可以专门加个配置项。

**Comment by yjnu** [comment]
> 这个交互每个人的需求不同的，比如我会在列表页同时点好几个相关的标签页打开，如果每次点击都跳转的话，我还要返回列表页再一个个这么操作，很麻烦的。
> 
> 当然，这个得看看点击跳转需求的人多不多，如果多的话可以专门加个配置项。

可以效仿书签，左键前台打开，中键后台打开

**Comment by web-dahuyou** [comment]
这个建议不错，我打算左键前台打开，ctrl/alt + 单击后台打开。
