### ISSUE TITLE
[BUG] 会在每个页面注入元素

### ISSUE THREAD

**Issue by Andyear** [web-dahuyou/NiceTab#54]
扩展会在每个页面都注入nicetab-message元素，会导致一些网站布局异常
![image](https://github.com/user-attachments/assets/b57d7b63-fbe7-4b23-be74-7d4b37b8c059)
![image](https://github.com/user-attachments/assets/046aca7f-a14c-467a-b585-bf2fd0750203)

**Comment by web-dahuyou** [comment]
这个我已经发现了，改动没有提交，准备跟webdav功能一起上
