### ISSUE TITLE
添加设置项，不自动跳转到后台管理

### ISSUE THREAD

**Issue by ChenDY2233** [web-dahuyou/NiceTab#6]
**希望添加设置项，可选【是、否】**
在浏览器右键，发送标签到nicetab的时候，是否跳转至后台管理

目前版本：`1.3.1`

![image](https://github.com/web-dahuyou/NiceTab/assets/39426660/d00dfe02-1634-4ecc-93fd-d867d763ca4d)

**Comment by web-dahuyou** [comment]
这个配置选项本来是有的，当时考虑到：在设置了发送标签页时不自动关闭标签页的情况下，如果不打开管理后台页，担心用户察觉不到，所以暂时给隐藏了该设置项，如果有这个需求，后面我给放开这个设置项。

![image](https://github.com/web-dahuyou/NiceTab/assets/22833786/b4026c4f-3eea-47c3-aa53-683290eb2d26)

**Comment by ChenDY2233** [comment]
两种方式发送标签页：
1、页面右键；
2、在扩展栏右键扩展；
这俩种方式的权限不一样是吗？
是否可以在页面上弹出类似论坛收藏帖子的提示效果，然后该信息会3s自动消失那样
如图：
![image](https://github.com/web-dahuyou/NiceTab/assets/39426660/1cdaaa21-ea75-477a-b970-6877106637f9)

**Comment by web-dahuyou** [comment]
你打开的页面不属于插件，插件默认只能控制自己的管理后台页面，想要在你的页面上提示，得申请页面权限，插件目前没有申请权限，后续计划在页面中注册快捷键，那时候可以申请权限

**Comment by ChenDY2233** [comment]
好的明白，谢谢。

**Comment by web-dahuyou** [comment]
v2.4.0 添加了快捷指令和配置项(发送标签页时是否打开管理后台),  如果配置不打开管理后台,并且也不关闭标签页,则会在当前页面message提示.
