### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Navasesh** [web-dahuyou/NiceTab#62]
不知道是不是版本更新了，点开ontab导入的标签报错，截图如下
![image](https://github.com/user-attachments/assets/fd8f1ad9-5e65-4498-9114-73735321be1f)

**Comment by web-dahuyou** [comment]
能去QQ群详细沟通下不, 这里不方便排查.

**Comment by catqaq** [comment]
请问进度，same error~

**Comment by web-dahuyou** [comment]
虽然不清楚你们的链接是什么格式的, 不过我加了一个错误catch处理

**Comment by web-dahuyou** [comment]
所以才弄个交流群，沟通会方便点，不过可能现在好多人都不用qq了
