### ISSUE TITLE
一些小的改善建议

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#67]
1. 建议增加显示版本号，目前版本更新频繁（好事儿），容易搞混。
2. 标签搜索功能：定位标签的时候位置不是很准确，就是不能直观发现定位的标签，常常是在附近（不是上一页就是下一页），我不得不再次使用页面查找才能定位， 建议是否把定位的标签行高亮或者其他更显眼的显示方式？

例行感谢忽悠哥的辛勤劳动和无私分享！

**Comment by web-dahuyou** [comment]
v2.5.4 已显示当前版本号和可升级的版本号
