### ISSUE TITLE
能否增加像 OneTab 一样在面板上增加发送全部标签页到 NiceTab

### ISSUE THREAD

**Issue by zeroskylian** [web-dahuyou/NiceTab#79]
而不是现在要右键发送

**Comment by web-dahuyou** [comment]
> 而且有个小建议, mac 的后台打开标签页能否换为 command 而不是 ctrl 或者增加一个自定义选项

目前使用的 Alt + 单击, 不是 ctrl , 后续可以加一个自定义选项, 在常用的那几个修饰键中选.

**Comment by web-dahuyou** [comment]
> 而不是现在要右键发送

- OneTab 这个按钮放在了列表页里, 但是这个得打开列表页才能点击啊, 不能做到在任何页面都能展示. 
- NiceTab 现在左键弹出面板支持配置化, 后续可以在popup弹窗面板中也放一个"发送全部标签页"按钮

**Comment by web-dahuyou** [comment]
插件有快捷键的，比手动点快多了

**Comment by web-dahuyou** [comment]
已经添加了，升级版本就行了

**Comment by web-dahuyou** [comment]
![image](https://github.com/user-attachments/assets/1b5cb9f8-1ddf-4fd1-93df-6358f4ef8d51)

尴尬了，按钮加了，忘了把点击事件加上，当时被其他事打断了，回来给忘了......
