### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#8]
期望尽快增加以下功能： 1. 发送标签页时，如果组名相同，则视为同一个组，在组内进行标签同步，而不是目前1.4.0版本的增加一个新的同名组。 2. 组内标签同步时，拒绝重复添加相同标签（设置可选项）。 3. 列表处增加按首字母排序组的功能。 4. 设置增加可选项：“如果某组未处于锁定状态，则当该组内无标签时，自动删除该组”。

**Comment by web-dahuyou** [comment]
1、2、4 功能可以有
3：按首字母排序的话，星标置顶与非星标的组该怎么排，这个后面看看有没有好的交互方式

**Comment by Mizanzhang** [comment]
建议各自排，即星标和星标排，非星标和非星标排，这时应该要引入一个置顶参数了。

**Comment by Mizanzhang** [comment]
能把1.2.4项功能开发往前排吗？ 我现在把nicetab当成存档库，没有上述功能，我只能这样操作：从列表恢复整组（顺便从列表中删除整组）》浏览，工作》把所有打开的网页分组》检查组名有没有重复（重复的又会被视为新组存档）》网页去重复》把所有分完组的网页发送到列表存档。
麻烦得要死。

**Comment by web-dahuyou** [comment]
最近工作比较忙，尽量抽空优化，功能后续会逐步添加。

**Comment by web-dahuyou** [comment]
#9 #10

**Comment by Mizanzhang** [comment]
UP你好，首先感谢你的辛勤劳动和快速响应！
试用了1.5.1，发现还是有问题，可能是我没有表达清楚。
我想要的去重功能，不是只针对发送的页面和组，而是将发送的页面或组与仓库已有的比较， 如果有重复的页面，就舍弃不再重复入仓，如果是组同名，就把发送组内的页面与仓库组内的页面比较，只入仓那些没有的页面到仓库同名组里面。这样仓库就不会像目前这样出现多个同名组。
还有，对仓库已有的组进行排序，这个功能应该是还没有添加吧？
