### ISSUE TITLE
[BUG]插件开深色模式会导致部分论坛字体变成白色..

### ISSUE THREAD

**Issue by uzcool** [web-dahuyou/NiceTab#84]
![20241122120344](https://github.com/user-attachments/assets/de4777fa-e64e-45b6-85fa-7ca466e12aae)
![20241122120443](https://github.com/user-attachments/assets/3d13eece-3594-4432-9f8b-5cc3a5bd6ca6)
换成浅色就正常显示

![20241122120551](https://github.com/user-attachments/assets/63c3ef69-743c-46e9-8873-d7e0d2088953)
试了2个论坛..都会出现..

https://www.52pojie.cn/
https://bbs.3dmgame.com/

不清楚是不是个例..

**Comment by web-dahuyou** [comment]
更新到2.5.8

**Comment by uzcool** [comment]
好的..
