### ISSUE TITLE
貌似性能不太行，优化也有点问题

### ISSUE THREAD

**Issue by Mylexstar** [web-dahuyou/NiceTab#86]
我大概有1000多标签页在同一个分组里，然后打开的时候卡住了，只能重启surface；
标签页移动的时候也有点问题，不能连续点击，我昨晚花了一个多小时才把300多标签页移动到另一分组；
这个扩展还是一个很好的扩展，特别是它的同步功能，希望能越来越好

**Comment by web-dahuyou** [comment]
- 你说 v2.5.9 版本吗，历史代码没注重性能，不敢大改，虽说是性能优化，其实只优化了很小一部分

**Comment by jurnlee** [comment]
期望增加分组全部展开，且可配置默认全部展开。养成习惯用分组管理~

**Comment by web-dahuyou** [comment]
> 期望增加分组全部展开，且可配置默认全部展开。养成习惯用分组管理~

这个功能最开始是有的，前期由于性能问题暂时给隐藏了

**Comment by web-dahuyou** [comment]
#87 更新了新版本 v2.5.10，
- 列表页全部展开按钮放出来了，新增了配置项； 
- 操作交互小优化
