### ISSUE TITLE
bug report：标签搜索定位偏差

### ISSUE THREAD

**Issue by Mizanzhang** [web-dahuyou/NiceTab#88]
搜索标签并在结果中点击某个标签定位时，定位位置不是很准确，就是不能直观看到定位的标签，页面常常是显示在该标签的附近（不是上一页就是下一页），我不得不再次使用页面查找才能准确定位，是否能优化一下该定位功能，把该标签滚到顶行/末行/居中，实在不行，能否把该标签行高亮或者其他更显眼的显示方式以便发现？

**Comment by web-dahuyou** [comment]
因为之前没有专门做标签页的选中功能，都是标签组级别的

**Comment by web-dahuyou** [comment]
v2.5.11 新增了标签页定位功能, 可以先使用仓库的压缩包尝试使用。
